name: "Terraform GitHub Actions"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master 
      - name: "Setup Terraform"
        uses: hashicorp/terraform-github-actions@master
        with:
          # terraform_version: 0.13.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true